version: "3"
networks:
  demo-network:
volumes:
  demo-postgresql:
    driver: local
  demo-keycloak:
    driver: local
services:
  postgresql:
    image: postgres:12.4
    container_name: demo-postgresql
    volumes:
      - demo-postgresql:/var/lib/postgresql/data/
    networks:
      - demo-network
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo31234
    ports:
      - 5432:5432
  keycloak:
    image: jboss/keycloak:10.0.0
    container_name: demo-keycloak
    networks:
      - demo-network
    ports:
      - 9090:8080
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgresql
      DB_DATABASE: keycloak
      DB_USER: demo
      DB_PASSWORD: demo31234
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: demo31234
    depends_on:
      - postgresql
