# Server
server:
  port: 8080
  address: localhost
# Spring Configs
spring:
  profiles:
    active:
    - dev
# Keycloak
keycloak:
  auth-server-url: http://localhost:9090/auth
  credentials:
    secret: 3cef5b1b-c24c-4f1b-ae92-c6e604aa0a5e
  ssl-required: external
#Extendz
credentials:
  keycloak:
    admin: admin
    password: demo31234
  
  
