spring:
  main:
    allow-bean-definition-overriding: true
  data:
    rest:
      base-path: /api
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
                 
logging:
  file:
    path: logs
  
keycloak:
  enabled: true
  realm: demo
  bearer-only: false
  resource: application
  public-client: false
  use-resource-role-mappings: true
  principal-attribute: preferred_username
